### ISSUE TITLE
希望能加上分组和拖拽调整顺序

### ISSUE THREAD

**Issue by htoooth** [czfadmin/bookmarks#1]
Thank you for the great tool provided by the big guy!
I hope that the following features can be added:
1. Double-click to jump, the jump icon is too small, not easy to click
2. Custom groupings
3. Drag and drop to adjust the order
4. There can be bookmarks based on projects, which can be stored in .vscode files

**Comment by czfadmin** [comment]
好主意
1. 双击好像不支持的, 只能支持单击(下个版本支持)
2. 下面的功能以后的版本准备支持下

**Comment by czfadmin** [comment]
- 在那时增加了已颜色分组的情况, 同时在这种情况下可以进行拖拽
- 可以开启`createJsonFile`配置, 可以在`.vscode`中创建 `.bookmarks.json`文件
![image](https://github.com/czfadmin/bookmarks/assets/13393959/e56621cf-77d7-491d-9bd4-4c94ca391a5b)

**Comment by htoooth** [comment]
我发现 vscode 的 workspace 不支持，我有多个项目加入到 worksapce 中，设置了书签没有起作用

**Comment by czfadmin** [comment]
这个可能有点问题, 我去排查下
