### ISSUE TITLE
【BUG】v0.0.18版本功能异常，所有命令无法使用

### ISSUE THREAD

**Issue by ProudRabbit** [czfadmin/bookmarks#10]
v0.0.18版本功能异常。
![image](https://github.com/czfadmin/bookmarks/assets/56437960/e120f3ab-0ef4-43fe-9ee7-f263f8103266)

![image](https://github.com/czfadmin/bookmarks/assets/56437960/59469899-837e-4df4-a809-1c9e998eb474)

**Comment by czfadmin** [comment]
我试了好像没有遇到这个问题

**Comment by ProudRabbit** [comment]
我在干净的虚拟机里只打开VScode，然后新建文件进行测试，也是同样的问题。

**Comment by czfadmin** [comment]
我去试一下看可不可以复现


> 我在干净的虚拟机里只打开VScode，然后新建文件进行测试，也是同样的问题。
> 
> VScode版本 版本: 1.85.2 (user setup) 提交: 8b3775030ed1a69b13e4f4c628c612102e30a681 日期: 2024-01-18T06:40:10.514Z Electron: 25.9.7 ElectronBuildId: 26354273 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19045

**Comment by czfadmin** [comment]
> 我在干净的虚拟机里只打开VScode，然后新建文件进行测试，也是同样的问题。
> 
> VScode版本 版本: 1.85.2 (user setup) 提交: 8b3775030ed1a69b13e4f4c628c612102e30a681 日期: 2024-01-18T06:40:10.514Z Electron: 25.9.7 ElectronBuildId: 26354273 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19045

确实复现了, 我去处理下

**Comment by czfadmin** [comment]
最近比较忙 哈哈哈哈,v0.0.19 修复了
