### ISSUE TITLE
使用行书签不能输入书签标签

### ISSUE THREAD

**Issue by ProudRabbit** [czfadmin/bookmarks#2]
![image](https://github.com/czfadmin/bookmarks/assets/56437960/fcf224ac-a7f2-4831-8a24-6a208c4c08e6)

使用行书签时，不能输入书签信息，需要先生成书签，然后再编辑书签标签才可以。

使用带有选择的书签就可以弹出书签标签输入栏，进行标签信息输入。

**Comment by czfadmin** [comment]
谢谢你的建议.
> 
> 使用行书签时，不能输入书签信息，需要先生成书签，然后再编辑书签标签才可以。
> 
本来打算支持也可以输入的, 但是考虑到大多数习惯会直接快捷命令面板中的 命令去增加一个`带有标签信息的书签`, 所以这个地方没有增加可以输入的标签的方式.
![image](https://github.com/czfadmin/bookmarks/assets/13393959/59ff00d2-2031-47ff-867a-42907086c8da)
不过可以在下个版本中可以将`bookmark-manager.toggleLineBookmarkWithLabel` 放到上下文菜单中,这样可以快捷的支持用户输入带有标签的行书签,

**Comment by ProudRabbit** [comment]
:+1: ：thank you

**Comment by czfadmin** [comment]
已经支持在上下文菜单中快捷创建带有标签的书签
