### ISSUE TITLE
能不能增加书签顺序调整？

### ISSUE THREAD

**Issue by htoooth** [czfadmin/bookmarks#23]
现在按颜色分组之后，书签顺序不能调整。

我想能不能增加：书签的顺序按我想要的顺序排，比如我可以拖拽调整书签在同一个分组中的位置。

**Comment by czfadmin** [comment]
这是可以当按照颜色分组的时候进行调整顺序,同时按照其他分组状况的时候也应当支持(仅在同一个文件,同一个类型的情况下)只是暂时没有实现 哈哈哈哈
