### ISSUE TITLE
Sort bookmarks by line number

### ISSUE THREAD

**Issue by GitGeertvo** [czfadmin/bookmarks#4]
Would it be possible to have bookmarks sorted by line numbers instead?

In this example:

![image](https://github.com/czfadmin/bookmarks/assets/102316282/dd63e93d-f12e-4346-b8fa-4d75517a1459)
Bookmark on Line 2 should show on top and bookmark on L 6

**Comment by czfadmin** [comment]
👍 That's a good suggestion. I'm ready to support it.

**Comment by czfadmin** [comment]
Already supported in new version(v0.0.16).
