### ISSUE TITLE
[BUG] remove text decoration but still display

### ISSUE THREAD

**Issue by htoooth** [czfadmin/bookmarks#41]
我关闭了文本装饰，但是显示了下划线

![image](https://github.com/czfadmin/bookmarks/assets/1717023/95ffabed-254a-4ec0-bdba-14d43b15594b)
![image](https://github.com/czfadmin/bookmarks/assets/1717023/cbbfc279-a5a8-4b3c-bf9a-e59f4d049fbc)

**Comment by czfadmin** [comment]
谢谢, 确实有这个问题, 已经修复 👍
