### ISSUE TITLE
希望能够编辑书签中现有的标签信息和备注信息。

### ISSUE THREAD

**Issue by ProudRabbit** [czfadmin/bookmarks#7]
1.  目前修改书签的标签和备注都是直接让输入信息，但是如果第一次输入的信息有错误，就需要重新输入一遍，而不能修改已有的信息。

![image](https://github.com/czfadmin/bookmarks/assets/56437960/13c091a4-a2a6-47a4-8751-60c83a60523e)

2. 在导航栏中希望增加一个按钮，用来修改书签的备注信息。

**Comment by czfadmin** [comment]
v0.0.18

**Comment by ProudRabbit** [comment]
更新到v0.0.18 版本后，命令都不能用了
![image](https://github.com/czfadmin/bookmarks/assets/56437960/ef4f0bb4-3b20-4492-990f-dd7a302746f7)


![image](https://github.com/czfadmin/bookmarks/assets/56437960/4090a4e4-4d97-4a25-9ded-1bfcaef7aa52)

**Comment by czfadmin** [comment]
看到了 在v0.0.19中问题解决了, 谢谢你的反馈,最近比较忙
